const mongoose = require("mongoose");
const { Schema } = mongoose;

const statTypeSchema = new Schema(
  {
    stat_id: Number,
    name: String,
    short_name: String,
    slug: String,
    type: String,
    tier: Number,
    price: Number,
    gold_price: Number,
    not_in_shop: Boolean,
    nation: String,
    tank_id: String,
    forward_speed: Number,
    reverse_speed: Number,
    hull_armor_front: Number,
    hull_armor_side: Number,
    hull_armor_rear: Number,
    turret_armor_front: Number,
    turret_armor_side: Number,
    turret_armor_rear: Number,
    chassis_rotation_speed: Number,
    turret_rotation_speed: Number,
    view_range: Number,
    gun_name: String,
    elevation: Number,
    depression: Number,
    max_ammo: Number,
    reload_time: Number,
    aim_time: Number,
    dispersion: Number,
    clip_size: Number,
    burst_size: Number,
    shell_icon: String,
    shell_type: String,
    caliber: Number,
    explosion_radius: Number,
    damage: Number,
    module_damage: Number,
    speed: Number,
    penetration: Number,
    power: Number,
    fire_chance: Number,
    radio_range: Number,
    health: Number,
    weight: Number,
    potential_damage: Number,
    dpm: Number,
    pwr: Number,
    stationary_camo: Number,
    moving_camo: Number,
    chassis: Number,
    turret: Number,
    gun: Number,
    shell: Number,
    engine: Number,
    radio: Number,
  },
  {
    collection: "stats",
  }
);

module.exports = mongoose.model("StatTypeModel", statTypeSchema);
